language: perl

perl:
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

install:
   - unset PERL_CPANM_OPT
   - export CPAN_MIRROR_URL=http://cpan.stratopan.com
   - cpanm --mirror $CPAN_MIRROR_URL --quiet --notest Dist::Zilla
   - dzil authordeps | cpanm $CPAN_MIRROR_URL --quiet --notest 
   - dzil listdeps   | cpanm $CPAN_MIRROR_URL --quiet --notest

script:
   - export HARNESS_OPTIONS='j:c'
   - dzil smoke --release --author
