language: perl

perl:
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

install:
   - unset PERL_CPANM_OPT
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - dzil authordeps | cpanm --quiet --notest --skip-satisfied
   - dzil listdeps   | cpanm --quiet --notest

script:
   - export PINTO_RUNNING_UNDER_TRAVIS=1
   - dzil smoke --release --author
